{% set name = "pyquil" %}
{% set version = "2.12.0" %}
{% set sha256 = "82c4218142d79b5cc2230d80054a4c5c56b1301094bc1cf8faee786667590477" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python
    - numpy
    - six
    - antlr-python-runtime
    - requests
    - networkx
    - rpcq
    - immutables == 0.6

test:
  imports:
    - pyquil
    - pyquil.gates

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Python library for quantum programming using Quil'
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - karalekas
