{% set name = "pyquil" %}
{% set version = "2.23.2" %}
{% set sha256 = "d90a85b03ac83b3e18e24a1a5c21adc24a029aecbe322c6c40349fd7ca7570e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python
    - numpy
    - antlr-python-runtime >=4.7.2,<4.8
    - requests
    - networkx >=2.0.0
    - rpcq >=3.0.0
    - immutables ==0.6

test:
  imports:
    - pyquil
    - pyquil.gates

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
