travis:
  secure:
    BINSTAR_TOKEN: pyUjHtsbfylEmAMB+hPfkMmw5kPIdK9biXgPPEL/lFwbboNm7CQ7eMwAgdb3PQ3GkQAg186ZDi+aacaF5XaWOR0u8ZBHWLF+1r1eUPD/Df98hSoH6ZO61Lk0/zHXw2Mp1QbHERe4LKogf1kSx6gQnyrsoWBuWvtok5ud2jIRif8b1y/GB4kWUCls7GsG05Zp0lnUrZHE9lDGuJKeGmG8IAkKPlI4mSL+e8INRitgVPvFzqGDyXqjLdxQP4HHSQPNCJwbggh9Z5oMqZS7bDlTAd43q2ov/MKVtl1YERXr3IylasMQ2fwR6Aqcp0L3h3obg7wCKSRHrxbpdIUbOTAndOIGUKGpE94lTRAU5XZ+CWHCVBHr5uCKKBtnfUqb4dcYWbNV7HDDHgCjhAF7RyqNMzX7N1d/vT01jIgrfT8MmReWDcPcs3bVRbgI4PQBjw/gMWVhyTsKEnVMZZ5NCU01CughWvr/hm2abfsyK+XrPgZr6nglgNvEaq+bzTFBc7OuJP5u3SrgwpUaj6MEbHoPWYTvYHHv8o4nU/4EBc4B3LJSSnSIAL3vU13p6fIQ6kQsE86K/RRIk7Arrszk1wzTibcicWOIjSQWXOuTE4gY+fN48uaL8aQAF6KvxXk4+g/q4Q9MzegV8yz99d8RdMGxx/DXU1zlxDYTqEn3CIGy4PA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
