travis:
  secure:
    BINSTAR_TOKEN: PzDZPzTyLPdNnWpnTZ1W0SdWJq4kj6BZbfODr3eNZe7grTMX0HDnH1fPHYQTV5XjlPqu4qBM7KviMBKexG3kGpcCyzVfUDXtm9EblB1YO2MFHy2K4ZgEZbAHbhnmjHjB23OwTPRbOx9QcnExfEzVq3iKc6TgObQdb8v31/VKgsoEOcT73lD/QT12Gv1ow6TgT6caGLzJtCStbIJqp5YH16sqkpKJIJS6I7fsunv0shIF9uhCuEc5eoWYoBry+OF4dC/Ld4y10lvQJfZxoYvecUiXxjyAaFuYZjPHcfOJ6dldZ0II9HPH4DcEp0WYyFuqhoD0afHX/mR4FUtqSTa4n8IyVZCySCBVPI1u8UMyOapEa7bzuDlXSsw3dUso0ZtbNquXE0PXmRCdZ+Z/ECBORRN3urs0w9UxguXXlKT0rK4xFJjpHox31V47/BSJYDgy1RA2eDlX83kWFEToQfk23/iYEMRsIoo9CYuYjwJhn0fAWtmQo3wJn/u+21+/ak0sv6qg8iRQ7ZGOsOA0qiTfOVrsvkWBGlYj4yzxesrK+p9Q1ewc74nRRSgcfT0rMT6neFdHhCPB/gijt1LI3T0SSDZmAEqSIC76ga46s8jmTg+hrBkgLTVSSp+O3yIqg4Zhu4DBC1ADIK00WinzUP1cK6xagO2ZKl+Ku6gl77+Uaos=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
